/*
Copyright 2026 The Kubernetes authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MemcachedSpecApplyConfiguration represents a declarative configuration of the MemcachedSpec type for use
// with apply.
//
// MemcachedSpec defines the desired state of Memcached
type MemcachedSpecApplyConfiguration struct {
	// Size defines the number of Memcached instances
	Size *int32 `json:"size,omitempty"`
	// ContainerPort defines the port exposed by the Memcached container
	ContainerPort *int32 `json:"containerPort,omitempty"`
}

// MemcachedSpecApplyConfiguration constructs a declarative configuration of the MemcachedSpec type for use with
// apply.
func MemcachedSpec() *MemcachedSpecApplyConfiguration {
	return &MemcachedSpecApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *MemcachedSpecApplyConfiguration) WithSize(value int32) *MemcachedSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithContainerPort sets the ContainerPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerPort field is set to the value of the last call.
func (b *MemcachedSpecApplyConfiguration) WithContainerPort(value int32) *MemcachedSpecApplyConfiguration {
	b.ContainerPort = &value
	return b
}
