/*
Copyright 2026 The Kubernetes authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MemcachedStatusApplyConfiguration represents a declarative configuration of the MemcachedStatus type for use
// with apply.
//
// MemcachedStatus defines the observed state of Memcached.
type MemcachedStatusApplyConfiguration struct {
	// Conditions represent the current state of the Memcached deployment
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MemcachedStatusApplyConfiguration constructs a declarative configuration of the MemcachedStatus type for use with
// apply.
func MemcachedStatus() *MemcachedStatusApplyConfiguration {
	return &MemcachedStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MemcachedStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MemcachedStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
