[build]
    base = "docs/book"
    command = "GO_VERSION=1.23.0 ./install-and-build.sh"
    publish = "docs/book/book"
    functions = "docs/book/functions"

# TODO(directxman12): I don't know why, but this (functions) stanza is in the
# docs and local `netlify dev`, but the above one (under build) is used by the
# online version :-/

# used to handle the split between v2 and v3+ download links
[functions]
    # relative to base directory
    directory = "functions"

# Standard Netlify redirects
[[redirects]]
    from = "https://kubebuilder.netlify.com/*"
    to = "https://book.kubebuilder.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://go.kubebuilder.io/*"
    to = "https://go.kubebuilder.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://kubebuilder.netlify.com/*"
    to = "http://book.kubebuilder.io/:splat"
    status = 301
    force = true

# kubebuilder binary (v3+) and tarball (< v3) redirects.
[[redirects]]
    from = "https://go.kubebuilder.io/dl/*"
    to = "https://go.kubebuilder.io/releases/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/releases"
    to = "https://github.com/kubernetes-sigs/kubebuilder/releases"
    status = 302
    force = true

# Development branch redirect.
[[redirects]]
    from = "https://go.kubebuilder.io/releases/master/:os/:arch"
    to = "https://storage.googleapis.com/kubebuilder-release/kubebuilder_master_:os_:arch.tar.gz"
    status = 302
    force = true

# Latest redirects.
[[redirects]]
    from = "https://go.kubebuilder.io/releases/latest"
    to = "https://github.com/kubernetes-sigs/kubebuilder/releases/latest"
    status = 302
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/releases/latest/:os"
    to = "https://go.kubebuilder.io/releases/latest/:os/amd64"
    status = 302
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/releases/latest/:os/:arch"
    to = "https://github.com/kubernetes-sigs/kubebuilder/releases/latest/download/kubebuilder_:os_:arch"
    status = 302
    force = true

# general release redirects
[[redirects]]
    from = "https://go.kubebuilder.io/releases/:version"
    to = "https://github.com/kubernetes-sigs/kubebuilder/releases/v:version"
    status = 302
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/releases/:version/:os"
    to = "https://go.kubebuilder.io/releases/:version/:os/amd64"
    status = 302
    force = true

# release download redirect
[[redirects]]
    from = "https://go.kubebuilder.io/releases/:version/:os/:arch"
    # I don't quite know why, but netlify (or at least the dev mode) *insists*
    # on eating every other query parameter, so just use paths instead
    to = "/.netlify/functions/handle-version/releases/:version/:os/:arch"
    # 200 --> don't redirect to the function then to whereever it says,
    # just pretend like the function is mounted directly here
    status = 200
    force = true

# Tools redirects.
[[redirects]]
    from = "https://go.kubebuilder.io/test-tools"
    to = "https://storage.googleapis.com/kubebuilder-tools"
    status = 302
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/test-tools/:k8sversion"
    to = "https://storage.googleapis.com/kubebuilder-tools/?prefix=kubebuilder-tools-:k8sversion"
    status = 302
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/test-tools/:k8sversion/:os"
    to = "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-:k8sversion-:os-amd64.tar.gz"
    status = 302
    force = true

[[redirects]]
    from = "https://go.kubebuilder.io/test-tools/:k8sversion/:os/:arch"
    to = "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-:k8sversion-:os-:arch.tar.gz"
    status = 302
    force = true

# custom 404 handling -- this may need to be last -- netlify docs are unclear
[[redirects]]
    from = "/*"
    to = "/404.html"
    status = 404
