{{ if eq .Spec.Webhooks.CertificateSource.Type "certManager" }}
# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager 0.11 check https://docs.cert-manager.io/en/latest/tasks/upgrading/index.html for 
# breaking changes
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Name }}-selfsigned-issuer
  namespace: {{ .Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Name }}-serving-cert
  namespace: {{ .Namespace }}
spec:
  dnsNames:
  - webhook-service.{{ .Namespace }}.svc
  - webhook-service.{{ .Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize
---
{{ end }}
