{{- if .Spec.ControllerManager.ComponentConfig.Enable  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: {{ .Namespace }}
  labels:
    control-plane: controller-manager
data:
  controller_manager_config.yaml: ""
---
{{ end }}