{{- if eq .Spec.Webhooks.CertificateSource.Type "dev" }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ .Namespace }}
data:
  tls.key: {{ .Status.CertKey }}
  tls.crt: {{ .Status.CertCA }}
---
{{ end }}
