/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package yaml

import (
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/spf13/afero"
	"sigs.k8s.io/yaml"

	"sigs.k8s.io/kubebuilder/v4/pkg/config"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store"
	"sigs.k8s.io/kubebuilder/v4/pkg/machinery"
)

const (
	// DefaultPath is the default path for the configuration file
	DefaultPath = "PROJECT"

	// Comment for 'PROJECT' config file
	commentStr = `# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
# More info: https://book.kubebuilder.io/reference/project-config.html
`
)

// yamlStore implements store.Store using a YAML file as the storage backend
// The key is translated into the YAML file path
type yamlStore struct {
	// fs is the filesystem that will be used to store the config.Config
	fs afero.Fs
	// mustNotExist requires the file not to exist when saving it
	mustNotExist bool

	cfg config.Config
}

// New creates a new configuration that will be stored at the provided path
func New(fs machinery.Filesystem) store.Store {
	return &yamlStore{fs: fs.FS}
}

// New implements store.Store interface
func (s *yamlStore) New(version config.Version) error {
	cfg, err := config.New(version)
	if err != nil {
		return fmt.Errorf("could not create config: %w", err)
	}

	s.cfg = cfg
	s.mustNotExist = true
	return nil
}

// Load implements store.Store interface
func (s *yamlStore) Load() error {
	return s.LoadFrom(DefaultPath)
}

type versionedConfig struct {
	Version config.Version `json:"version"`
}

// pathClass describes what is at a path.
type pathClass int

const (
	pathMissing pathClass = iota
	pathRegularFile
	pathDirectory
	pathIrregularFile
	pathSymbolicLink
)

// String returns a human-readable description of the path class.
func (c pathClass) String() string {
	switch c {
	case pathRegularFile:
		return "a regular file"
	case pathDirectory:
		return "a directory"
	case pathSymbolicLink:
		return "a symbolic link"
	case pathIrregularFile:
		return "not a regular file"
	default:
		return ""
	}
}

// classify reports what is at the path after following a final symbolic link.
func classify(fs afero.Fs, path string) (pathClass, error) {
	info, err := fs.Stat(path)

	return classifyInfo(path, info, err)
}

// classifyNoFollow reports a final symbolic link without following it when the filesystem supports
// Lstat. This lets callers distinguish a link with a missing target from a missing path.
func classifyNoFollow(fs afero.Fs, path string) (pathClass, error) {
	lstater, ok := fs.(afero.Lstater)
	if !ok {
		return classify(fs, path)
	}

	info, _, err := lstater.LstatIfPossible(path)

	return classifyInfo(path, info, err)
}

// classifyInfo maps file information and a stat error to a path class.
func classifyInfo(path string, info os.FileInfo, err error) (pathClass, error) {
	switch {
	case errors.Is(err, os.ErrNotExist):
		return pathMissing, nil
	case err != nil:
		return pathMissing, fmt.Errorf("failed to check %q: %w", path, err)
	case info.Mode()&os.ModeSymlink != 0:
		return pathSymbolicLink, nil
	case info.Mode().IsRegular():
		return pathRegularFile, nil
	case info.IsDir():
		return pathDirectory, nil
	default:
		return pathIrregularFile, nil
	}
}

// checkReadable returns an error when the path cannot be read as a configuration file. It reports
// os.ErrNotExist only when nothing is at the path, so that callers can tell a project that was
// never initialized from one whose configuration path holds something else.
func checkReadable(fs afero.Fs, path string) error {
	// The link is followed, so a link to a configuration file is read as one.
	class, err := classify(fs, path)
	if err != nil {
		return err
	}

	if class == pathMissing {
		// A link with a missing target also reads as missing, so report the link instead.
		linkClass, linkErr := classifyNoFollow(fs, path)
		if linkErr != nil || linkClass != pathSymbolicLink {
			return fmt.Errorf("failed to read %q file: %w", path, os.ErrNotExist)
		}
		class = linkClass
	}

	if class != pathRegularFile {
		return fmt.Errorf("%q is %s", path, class)
	}

	return nil
}

// checkSavePath verifies that the path can be used to save a configuration. It accepts a missing
// path for a new configuration and a regular file for an update. Other path types are rejected
// when the filesystem can identify them.
func checkSavePath(fs afero.Fs, path string, mustNotExist bool) error {
	class, err := classifyNoFollow(fs, path)
	if err != nil {
		return err
	}

	switch class {
	case pathRegularFile:
		if mustNotExist {
			return fmt.Errorf("configuration already exists in %q", path)
		}
		return nil
	case pathSymbolicLink, pathDirectory, pathIrregularFile:
		return fmt.Errorf("cannot save configuration to %q: path is %s", path, class)
	default:
		return nil
	}
}

// LoadFrom implements store.Store interface
func (s *yamlStore) LoadFrom(path string) error {
	s.mustNotExist = false

	// Only a regular file can carry configuration data.
	if err := checkReadable(s.fs, path); err != nil {
		return store.LoadError{Err: err}
	}

	// Read the file
	in, err := afero.ReadFile(s.fs, path)
	if err != nil {
		return store.LoadError{Err: fmt.Errorf("failed to read %q file: %w", path, err)}
	}

	// Check the file version
	var versioned versionedConfig
	if err = yaml.Unmarshal(in, &versioned); err != nil {
		return store.LoadError{Err: fmt.Errorf("failed to determine config version: %w", err)}
	}

	// Create the config object
	var cfg config.Config
	cfg, err = config.New(versioned.Version)
	if err != nil {
		return store.LoadError{Err: fmt.Errorf("failed to create config for version %q: %w", versioned.Version, err)}
	}

	// Unmarshal the file content
	if err := cfg.UnmarshalYAML(in); err != nil {
		return store.LoadError{Err: fmt.Errorf("failed to unmarshal config at %q: %w", path, err)}
	}

	s.cfg = cfg
	return nil
}

// Save implements store.Store interface
func (s yamlStore) Save() error {
	return s.SaveTo(DefaultPath)
}

// SaveTo implements store.Store interface
func (s yamlStore) SaveTo(path string) error {
	// If yamlStore is unset, none of New, Load, or LoadFrom were called successfully
	if s.cfg == nil {
		return store.SaveError{Err: fmt.Errorf("undefined config, use one of the initializers: New, Load, LoadFrom")}
	}

	// Only a missing path or a regular file can be used for saving. New configurations require
	// the path to be missing, while existing configurations may update a regular file.
	if err := checkSavePath(s.fs, path, s.mustNotExist); err != nil {
		return store.SaveError{Err: err}
	}

	// Marshall into YAML
	content, err := s.cfg.MarshalYAML()
	if err != nil {
		return store.SaveError{Err: fmt.Errorf("failed to marshal to YAML: %w", err)}
	}

	// Prepend warning comment for the 'PROJECT' file
	content = append([]byte(commentStr), content...)

	// Write the marshalled configuration
	// afero.WriteFile uses O_CREATE|O_TRUNC, so it is appropriate when updating an existing regular
	// file. New configurations need O_EXCL, which afero.WriteFile does not expose, to prevent an
	// existing path from being overwritten after the path check.
	var writeErr error
	if s.mustNotExist {
		writeErr = s.writeNew(path, content)
	} else {
		writeErr = afero.WriteFile(s.fs, path, content, machinery.DefaultFilePermission)
	}
	if writeErr != nil {
		return store.SaveError{Err: fmt.Errorf("failed to save configuration to %q: %w", path, writeErr)}
	}

	return nil
}

// writeNew creates a configuration only if the path is still unused. If kubebuilder init sees no
// PROJECT and another process creates PROJECT before the write—for example, a symbolic link to
// /tmp/important.yaml—O_EXCL makes the write fail instead of overwriting that file or following
// the link.
func (s yamlStore) writeNew(path string, content []byte) error {
	file, err := s.fs.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, machinery.DefaultFilePermission)
	if err != nil {
		return fmt.Errorf("failed to open the file: %w", err)
	}

	n, err := file.Write(content)
	if err == nil && n != len(content) {
		err = io.ErrShortWrite
	}

	if closeErr := file.Close(); err == nil {
		err = closeErr
	}

	return err
}

// Config implements store.Store interface
func (s yamlStore) Config() config.Config {
	return s.cfg
}
