/*
Copyright 2026 The Kubernetes authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1

// PrawnSpecApplyConfiguration represents a declarative configuration of the PrawnSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// PrawnSpec defines the desired state of Prawn
type PrawnSpecApplyConfiguration struct {
	// foo is an example field of Prawn. Edit prawn_types.go to remove/update
	Foo *string `json:"foo,omitempty"`
}

// PrawnSpecApplyConfiguration constructs a declarative configuration of the PrawnSpec type for use with
// apply.
func PrawnSpec() *PrawnSpecApplyConfiguration {
	return &PrawnSpecApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *PrawnSpecApplyConfiguration) WithFoo(value string) *PrawnSpecApplyConfiguration {
	b.Foo = &value
	return b
}
