// Code generated by lister-gen. DO NOT EDIT.

package v1

// TestKindListerExpansion allows custom methods to be added to
// TestKindLister.
type TestKindListerExpansion interface{}

// TestKindNamespaceListerExpansion allows custom methods to be added to
// TestKindNamespaceLister.
type TestKindNamespaceListerExpansion interface{}
