/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-sigs/kubebuilder/test/webhooks/apis/foobar/v1alpha1"
	scheme "github.com/kubernetes-sigs/kubebuilder/test/webhooks/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FooBarsGetter has a method to return a FooBarInterface.
// A group's client should implement this interface.
type FooBarsGetter interface {
	FooBars(namespace string) FooBarInterface
}

// FooBarInterface has methods to work with FooBar resources.
type FooBarInterface interface {
	Create(*v1alpha1.FooBar) (*v1alpha1.FooBar, error)
	Update(*v1alpha1.FooBar) (*v1alpha1.FooBar, error)
	UpdateStatus(*v1alpha1.FooBar) (*v1alpha1.FooBar, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FooBar, error)
	List(opts v1.ListOptions) (*v1alpha1.FooBarList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FooBar, err error)
	FooBarExpansion
}

// fooBars implements FooBarInterface
type fooBars struct {
	client rest.Interface
	ns     string
}

// newFooBars returns a FooBars
func newFooBars(c *FoobarV1alpha1Client, namespace string) *fooBars {
	return &fooBars{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fooBar, and returns the corresponding fooBar object, and an error if there is any.
func (c *fooBars) Get(name string, options v1.GetOptions) (result *v1alpha1.FooBar, err error) {
	result = &v1alpha1.FooBar{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("foobars").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FooBars that match those selectors.
func (c *fooBars) List(opts v1.ListOptions) (result *v1alpha1.FooBarList, err error) {
	result = &v1alpha1.FooBarList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("foobars").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fooBars.
func (c *fooBars) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("foobars").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fooBar and creates it.  Returns the server's representation of the fooBar, and an error, if there is any.
func (c *fooBars) Create(fooBar *v1alpha1.FooBar) (result *v1alpha1.FooBar, err error) {
	result = &v1alpha1.FooBar{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("foobars").
		Body(fooBar).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fooBar and updates it. Returns the server's representation of the fooBar, and an error, if there is any.
func (c *fooBars) Update(fooBar *v1alpha1.FooBar) (result *v1alpha1.FooBar, err error) {
	result = &v1alpha1.FooBar{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("foobars").
		Name(fooBar.Name).
		Body(fooBar).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *fooBars) UpdateStatus(fooBar *v1alpha1.FooBar) (result *v1alpha1.FooBar, err error) {
	result = &v1alpha1.FooBar{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("foobars").
		Name(fooBar.Name).
		SubResource("status").
		Body(fooBar).
		Do().
		Into(result)
	return
}

// Delete takes name of the fooBar and deletes it. Returns an error if one occurs.
func (c *fooBars) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("foobars").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fooBars) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("foobars").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fooBar.
func (c *fooBars) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FooBar, err error) {
	result = &v1alpha1.FooBar{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("foobars").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
