// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/kubernetes-sigs/kubebuilder/test/projects/validations/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// TestKinds returns a TestKindInformer.
	TestKinds() TestKindInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// TestKinds returns a TestKindInformer.
func (v *version) TestKinds() TestKindInformer {
	return &testKindInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
