// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	apps_v1 "github.com/kubernetes-sigs/kubebuilder/test/projects/validations/pkg/apis/apps/v1"
	versioned "github.com/kubernetes-sigs/kubebuilder/test/projects/validations/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubernetes-sigs/kubebuilder/test/projects/validations/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kubernetes-sigs/kubebuilder/test/projects/validations/pkg/client/listers/apps/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TestKindInformer provides access to a shared informer and lister for
// TestKinds.
type TestKindInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TestKindLister
}

type testKindInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTestKindInformer constructs a new informer for TestKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTestKindInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTestKindInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTestKindInformer constructs a new informer for TestKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTestKindInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1().TestKinds(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1().TestKinds(namespace).Watch(options)
			},
		},
		&apps_v1.TestKind{},
		resyncPeriod,
		indexers,
	)
}

func (f *testKindInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTestKindInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *testKindInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apps_v1.TestKind{}, f.defaultInformer)
}

func (f *testKindInformer) Lister() v1.TestKindLister {
	return v1.NewTestKindLister(f.Informer().GetIndexer())
}
