name: External Plugin

on:
  push:
    paths:
      - 'pkg/'
      - 'docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin'
      - '.github/workflows/external-plugin.yml'
  pull_request:
    paths:
      - 'pkg/'
      - 'docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin'
      - '.github/workflows/external-plugin.yml'

jobs:
  external:
    name: Verify external plugin
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make test-external-plugin

