name: External Plugin

on:
  push:
    paths:
      - 'pkg/'
      - 'docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin'
      - '.github/workflows/external-plugin.yml'
  pull_request:
    paths:
      - 'pkg/'
      - 'docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin'
      - '.github/workflows/external-plugin.yml'

permissions: {}
  
jobs:
  external:
    name: Verify external plugin
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make test-external-plugin

