# This test ensure that the legacy webhook path
# still working. The option is deprecated
# and should be removed when we no longer need
# to support go/v4 plugin.
name: Legacy Webhook Path

on:
  push:
    paths:
      - 'testdata/**'
      - '.github/workflows/legacy-webhook-path.yml'
  pull_request:
    paths:
      - 'testdata/**'
      - '.github/workflows/legacy-webhook-path.yml'

jobs:
  webhook-legacy-path:
    permissions:
      contents: read
    name: Verify Legacy Webhook Path
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
      - name: Run make test-legacy
        run: make test-legacy

