name: Lint GitHub Actions Workflows
on:
  pull_request:
    paths: 
     - '**/workflows/*.yml'
jobs:
  zizmor:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor on kubebuilder GitHub Actions workflows
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false
          inputs: .github/
  
  pinact:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26'

      - name: Install pinact
        run: |
          go install github.com/suzuki-shunsuke/pinact/v3/cmd/pinact@v3.5.0

      - name: Display changed workflows in PR
        run: |
          git diff --name-only origin/${GITHUB_BASE_REF} HEAD
          
      - name: Run pinact on changed workflow files
        run: |
          git diff --name-only origin/${GITHUB_BASE_REF} HEAD \
          | grep -E 'workflows/.*\.ya?ml$' \
          | xargs pinact run --diff --check --verify              
