name: Lint Samples

on:
  push:
    paths:
      - 'testdata/**'
      - 'docs/book/src/**/testdata/**'
      - '.github/workflows/lint-sample.yml'
  pull_request:
    paths:
      - 'testdata/**'
      - 'docs/book/src/**/testdata/**'
      - '.github/workflows/lint-sample.yml'

permissions: {}

jobs:
  lint-samples:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [
          "testdata/project-v4",
          "testdata/project-v4-with-plugins",
          "testdata/project-v4-multigroup",
          "docs/book/src/cronjob-tutorial/testdata/project",
          "docs/book/src/getting-started/testdata/project",
          "docs/book/src/multiversion-tutorial/testdata/project"
        ]
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: Prepare ${{ matrix.folder }}
        working-directory: ${{ matrix.folder }}
        run: go mod tidy
      - name: Check linter configuration
        working-directory: ${{ matrix.folder }}
        run: make lint-config
      - name: Run linter
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          working-directory: ${{ matrix.folder }}
      - name: Run linter via makefile target
        working-directory: ${{ matrix.folder }}
        run: make lint

