name: run-test-e2e-for-project-v4-sample

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.21'

      - name: Create kind cluster
        run: kind create cluster
        
      - name: Prepare the environment
        run: |
          KUSTOMIZATION_FILE_PATH="testdata/project-v4/config/default/kustomization.yaml"
          sed -i '25s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '27s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '42s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '46,143s/^#//' $KUSTOMIZATION_FILE_PATH
      
      - name: Test
        run: |
          cd testdata/project-v4
          go mod tidy
          make test-e2e
